// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEXxPqslWth-ppWglGpshoLWNGx5AQt2k',
    appId: '1:288926138456:web:d9192931b3932c2da9ca2d',
    messagingSenderId: '288926138456',
    projectId: 'rock-climbing-76ee3',
    authDomain: 'rock-climbing-76ee3.firebaseapp.com',
    databaseURL: 'https://rock-climbing-76ee3-default-rtdb.firebaseio.com',
    storageBucket: 'rock-climbing-76ee3.firebasestorage.app',
    measurementId: 'G-61ZN6VBH3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4qcrjVdskjWkguZPzTh7BSr_Kpsv0kU',
    appId: '1:288926138456:android:d7e3c98ff2d899fea9ca2d',
    messagingSenderId: '288926138456',
    projectId: 'rock-climbing-76ee3',
    databaseURL: 'https://rock-climbing-76ee3-default-rtdb.firebaseio.com',
    storageBucket: 'rock-climbing-76ee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdRdGUM1-_4g_5mT7cuUPepw6y9B_FyWY',
    appId: '1:288926138456:ios:34f312ce97bbbc4ca9ca2d',
    messagingSenderId: '288926138456',
    projectId: 'rock-climbing-76ee3',
    databaseURL: 'https://rock-climbing-76ee3-default-rtdb.firebaseio.com',
    storageBucket: 'rock-climbing-76ee3.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdRdGUM1-_4g_5mT7cuUPepw6y9B_FyWY',
    appId: '1:288926138456:ios:34f312ce97bbbc4ca9ca2d',
    messagingSenderId: '288926138456',
    projectId: 'rock-climbing-76ee3',
    databaseURL: 'https://rock-climbing-76ee3-default-rtdb.firebaseio.com',
    storageBucket: 'rock-climbing-76ee3.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEXxPqslWth-ppWglGpshoLWNGx5AQt2k',
    appId: '1:288926138456:web:06eb74ebc151c8c8a9ca2d',
    messagingSenderId: '288926138456',
    projectId: 'rock-climbing-76ee3',
    authDomain: 'rock-climbing-76ee3.firebaseapp.com',
    databaseURL: 'https://rock-climbing-76ee3-default-rtdb.firebaseio.com',
    storageBucket: 'rock-climbing-76ee3.firebasestorage.app',
    measurementId: 'G-RKFZRYWMRQ',
  );
}
